### ISSUE TITLE
Error in file(file, ifelse(append, "a", "w")) :

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#1]
Trying out below example code:

``` R
library(R2BGLiMS)
data(JAM_Example)
jam.results <- JAM(
  marginal.betas=marginal.betas[snps.region1],
  X.ref=X.ref.region1,
  model.space.prior = list("Rate"=0.1, "Variables"=snps.region1),
  n=1000)
```

Gives error:

> Setting tau to max(n,P^2)
> java version "1.7.0_45"
> Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
> Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
> Error in file(file, ifelse(append, "a", "w")) : 
>   cannot open the connection
> In addition: Warning messages:
> 1: running command 'mkdir 'C:\Users\tdadaev\AppData\Local\Temp\RtmpAp26IC/R2BGLiMS_Arguments_Dec09120258'' had status 127 
> 2: In file(file, ifelse(append, "a", "w")) :
>   cannot open file 'C:\Users\tdadaev\AppData\Local\Temp\RtmpAp26IC/R2BGLiMS_Arguments_Dec09120258/R2BGLiMS_Arguments.txt': No such file or directory

Session info:

``` R
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R2BGLiMS_0.1-07-12-2015

loaded via a namespace (and not attached):
[1] tools_3.2.2
```

**Comment by zx8754** [comment]
This was Windows specific error, and it is now fixed.

**Comment by 15652939484** [comment]
would you share how to fix this problem. I meet this annoying problem sometimes, too.
Thx a lot!!!
