### ISSUE TITLE
All causal effects estimated by JAMMR are zero

### ISSUE THREAD

**Issue by igbucur** [pjnewcombe/R2BGLiMS#13]
Hello,

When running the examples for the JAMMR function, all estimated causal effects returned are zero, since commit 4df97e2f57c90c57c1f0ef76859cc2c7e4c8ec56.

Cheers,
Gabriel

**Comment by pjnewcombe** [comment]
Many apologies - I accidentally clicked closed the other issue when replying to you. Can't figure out just now how to re-open it but will be in touch later today in any case.

Thanks again, Gabriel.

Paul

**Comment by pjnewcombe** [comment]
Hi there,

We just uploaded another new version with some bugs fixed.

If this doesn't help, would it be possible to provide some more details please? I.e. I believe you were getting non-zero causal effect estimates with an older version of JAMMR, but the newer versions are giving you zero causal effect estimates?

If you prefer not to talk in detail on Github feel very free to reach out to myself - paul.newcombe@mrc-bsu.cam.ac.uk - and Apostolos (who wrote the JAMMR extension) apostolos.gkatzionis@mrc-bsu.cam.ac.uk, and we'd be happy to do what we can to help.

Paul

**Comment by igbucur** [comment]
Hi Paul,

I am not sure what caused the issue, but the last update seems to have fixed it. Thanks again for the prompt reply and debugging! 

Cheers,
Gabriel
