### ISSUE TITLE
Reference panel bigger than SNP list

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#2]
In example data _X.ref.region1_ we have 10 SNPs, when we supply _marginal.betas_ for only subset of SNPs, lets say 5 SNPs, `marginal.betas[1:5]` , program Errors out, presumable requiring reference SNPs to match with number of betas.

We could subset the reference to match the number of input betas, but it would be nice if this was done automagically.

``` R
library(R2BGLiMS)
data(JAM_Example)

binary.results <- JAM(
  marginal.betas=marginal.logors[1:5],
  X.ref=list(X.ref.region1),
  model.space.prior = list("a"=1, "b"=9, "Variables"=c(snps.region1) ),
  n.mil=1,
  n=n,
  n.cases=n.cases)
```

> Setting tau to max(n,P^2)
> 
> Log-Odds Ratios were provided.
> 
> Invoking the logistic -> linear transformation.java version "1.8.0_71"
> Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
> Java HotSpot(TM) Client VM (build 25.71-b15, mixed mode, sharing)
> Setting user specified argument  GaussianResidualVarianceInvGammaPrior_a 
> Setting user specified argument  GaussianResidualVarianceInvGammaPrior_b 
> 
> Writing temporary data files...
> 
> Writing a BGLiMS formatted datafile...
> Taking Cholesky decomposition of block 1 ...
> ...done... finished writing datafile.
> 
> ...finished writing temporary data files.
> 
> Data written in 0 hrs 0 mins and 0 seconds
> Calling BGLiMS...
> 
> Command: 
> java -jar "C:/Users/tdadaev/Documents/R/win-library/3.2/R2BGLiMS/BGLiMS/BGLiMS.jar" "C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed441b042fc_Jan29122239_Arguments.txt" "C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed45b362501_Jan29122239_Data.txt" "C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed45d665cc9_Jan29122239_Results.txt" 1000000 0 100 100000 1 1 1 0 -1 1 1 1 9 
> Exception in thread "main" java.util.InputMismatchException
>   at java.util.Scanner.throwFor(Unknown Source)
>   at java.util.Scanner.next(Unknown Source)
>   at java.util.Scanner.nextDouble(Unknown Source)
>   at Objects.Data.<init>(Data.java:477)
>   at bglims.BGLiMS.main(BGLiMS.java:81)
> 
> BGLiMS analysis finished in 0 hrs 0 mins and 0 seconds
> 
> Reading in the BGLiMS results file...
> Error in file(file, "rt") : cannot open the connection
> In addition: Warning messages:
> 1: running command 'java -jar "C:/Users/tdadaev/Documents/R/win-library/3.2/R2BGLiMS/BGLiMS/BGLiMS.jar" "C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed441b042fc_Jan29122239_Arguments.txt" "C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed45b362501_Jan29122239_Data.txt" "C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed45d665cc9_Jan29122239_Results.txt" 1000000 0 100 100000 1 1 1 0 -1 1 1 1 9' had status 1 
> 2: In file(file, "rt") :
>   cannot open file 'C:\Users\tdadaev\AppData\Local\Temp\RtmpM5CyTp\fileed45d665cc9_Jan29122239_Results.txt': No such file or directory

**Comment by pjnewcombe** [comment]
Great suggestion, and many thanks for flagging. I've updated JAM to do just this (with a message at the top of the output). Thanks again!

Paul
