### ISSUE TITLE
n.mil custom

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#3]
I am running below command with 10K ref panel, and 324 SNPs.

``` R
#data size
dim(X.ref.region)
# [1] 10000   324
length(marginal.logors)
# [1] 324

#JAM
binary.results <- JAM(
  marginal.betas = marginal.logors,
  X.ref = list(X.ref.region),
  model.space.prior = list("a"=1, "b"=9, "Variables"=c(snps.region)),
  n.mil = 1,
  n = n, # 89673 cases and controls?
  n.cases = n.cases # 53449 cases?
  )
```

Estimated time is about 70 minutes, while this is OK to wait for real data to run that long, I would like to be able to set 10K, 100K iterations for testing. I tired to set `n.mil=0.1`, thinking this would give me 100K iterations, but it was set to 1 million anyway.

Also, not sure I have the right numbers for `n` and `n.cases`. Could these be clarified in the manual better?

**Comment by pjnewcombe** [comment]
Sorry about this, that should work as you expect it to. 

If I run:

```
library(R2BGLiMS)
data(JAM_Example)
region1.results <- JAM(
  marginal.betas=marginal.betas[snps.region1],
  X.ref=X.ref.region1,
  model.space.prior = list("a"=1, "b"=1, "Variables"=snps.region1),
  n.mil=1,
  n=n)
```

Then I see:

`100000 / 1000000 iterations complete` etc in the output (the denominator is 10e6). But if I run:

```
library(R2BGLiMS)
data(JAM_Example)
region1.results <- JAM(
  marginal.betas=marginal.betas[snps.region1],
  X.ref=X.ref.region1,
  model.space.prior = list("a"=1, "b"=1, "Variables"=snps.region1),
  n.mil=0.1,
  n=n)
```

Then I see:

`10000 / 100000 iterations complete` etc in the output - the denominator is now 10e5, a factor of 10 smaller (and it clearly runs faster).

Do you see the issue when you run the examples above?

**Comment by pjnewcombe** [comment]
Oh and sorry your numbers for n and ncases look correct to me; n is the total sample size, and ncases the number of cases therein (i.e. ncases <= n). 

I agree this is not at all clear in the vignette - I will address this and thanks for highlighting. 

It's worth pointing out that there is much more detailed documentation inside the package. I.e. if you type

```
library(R2BGLiMS)
?JAM
```

**Comment by zx8754** [comment]
Thanks for explanation of `n` and `n.cases` arguments. I will test the `n.mil` options again, and will reopen this issue if it fails.

Just a suggestion, would it not make it clearer to change `n.mil` to `n.iter` and use numbers like 10000, 100000, 1000000 instead of 0.01, 0,1, 1, etc.?

**Comment by pjnewcombe** [comment]
Hi there - thanks for the suggestion. Yes, I see that is confusing. I will look at having both an `n.iter` and `n.mil.iter` argument, either of which can be used.

(Typically and what I'd recommend is that multiple million iterations are run where possible - so I'd like to keep an n.mil type argument to avoid entering lots of 0's and encourage lots of iterations)

**Comment by pjnewcombe** [comment]
Hi - just to let you know - I uploaded a new version which accepts either an `n.iter` or an `n.mil.iter` argument. Since `n.mil` is a substring of `n.mil.iter` it is backwards compatible with the old argument.

Best,
Paul

**Comment by zx8754** [comment]
Just to feedback, `n.mil=0.01` works as expected. I am also getting a message showing estimated time for 1M iterations which is very useful.

**Comment by pjnewcombe** [comment]
Great - and thanks! Good to know.
