### ISSUE TITLE
EOL missing

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#4]
After the results processed message, there is no EOL, see below. Makes it look like the script is still running.

``` R
...
Reading in the BGLiMS results file...
... finished reading BGLiMS results.

Cleaning up...
Results processed in 0 hrs 0 mins and 0 seconds>
```

**Comment by pjnewcombe** [comment]
Thank you for the catch. Yes, good suggestion. Now updated to do so.
