### ISSUE TITLE
Implement parallel option?

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#5]
As in [glmnet()](https://cran.r-project.org/web/packages/glmnet/vignettes/glmnet_beta.html) function below:

``` R
require(doMC)
registerDoMC(cores=2)
X = matrix(rnorm(1e4 * 200), 1e4, 200)
Y = rnorm(1e4)
system.time(cv.glmnet(X, Y))
##    user  system elapsed 
##   2.440   0.080   2.518
system.time(cv.glmnet(X, Y, parallel = TRUE))
##    user  system elapsed 
##   2.450   0.157   1.567
```

**Comment by pjnewcombe** [comment]
Hi Tokhir - interesting suggestion. I believe this option with cv.glmnet parallelises the analyses of the different cross-validation folds, which makes a lot of sense. Unfortunately, however, there is nothing obvious to parallelise in a similar way for JAM/R2BGLiMS. 

So I'll close this for now but will ponder. E.g. longer term I there could be an option to automatically run e.g. 2 MCMC seeds (for sensitivity analysis), and parallelise these over 2 cores. Also, for what it's worth JAM happily runs under commands from the R library `parallel' (which I often use to parallelise analyses of many simulation replicates).

Best,
Paul
