### ISSUE TITLE
Error: could not find function "new"

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#6]
`JAM()` function works fine when using interactive R session, but it fails with below error when run with Rscript.

> java version "1.7.0_19"
> OpenJDK Runtime Environment (rhel-2.3.9.1.el6_4-x86_64)
> OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)
> Error in R2BGLiMS(likelihood = which.blgims.jam.method, marginal.betas = marginal.betas,  : 
>   could not find function "new"
> Calls: JAM -> R2BGLiMS
> Execution halted

Similar issue was resolved by explicitly loading the library or using `::` column to call external function.
https://github.com/dhimmel/elevcan/issues/1#issuecomment-195447197

Maybe adding `methods::new(...)` instead of just `new(...)` at https://github.com/pjnewcombe/R2BGLiMS/blob/master/R/R2BGLiMS.R#L636 will solve this.

**Comment by pjnewcombe** [comment]
Thank you very much for letting me know - I had no idea - and providing the fix!! Now corrected and re-uploaded to github.

Best,
Paul
