### ISSUE TITLE
Check argument classes before running

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#8]
A very minor issue, I run below code:

```R
myLogisticResults <- R2BGLiMS(
  likelihood = "Logistic",
  data = myDat,
  outcome.var = "myOutcome",
  confounders = myConfounders,
  model.space.priors = list(a = 1, b = length(mySnps), Variables = mySnps),
  beta.priors = fixed.beta.priors,
  n.mil = 1,
  n = n)
```

But I forgot to create the `n` variable, so after running for 5 hours, it gives below error that `n` is not numeric. It would be nice to have a class check at the beginning of R2BGLiMS function, so that it would fail immediately, saying `n is missing` .

> Error in validObject(.Object) :
>   invalid class "R2BGLiMS_Results" object: invalid object for slot "n" in class "R2BGLiMS_Results": got class "function", should be or extend class "numeric"

Error says: `n` is a class of function, as it is part of dplyr package, `dplyr::n()`

**Comment by pjnewcombe** [comment]
Ah. Sorry about that!

Good suggestion, Tokhir. I will leave this open until I get a chance to do so.

Best,
Paul

**Comment by pjnewcombe** [comment]
I finally got round to adding this error check. Thanks again Tokhir.
