### ISSUE TITLE
Ensure TopModels returns 2 dimensional matrix

### ISSUE THREAD

**Issue by zx8754** [pjnewcombe/R2BGLiMS#9]
At the moment when there is no SNP in the top model it returns *numeric*, see below:
```R
> class(TopModels(binary.results))
[1] "numeric"
> class(TopModels(binary.results, remove.empty.cols = FALSE))
[1] "matrix"
```

**Comment by pjnewcombe** [comment]
Thank you Tokhir - this is now fixed in the version I just uploaded to GitHub.
